AVSBenchS4:
  ANNO_CSV: "/HOME//Single-source/s4_meta_data.csv"
  ANNO_CSV_SHUFFLE: "/HOME//Single-source/s4_meta_data_shuffled.csv"
  DIR_IMG: "/HOME//Single-source/s4_data/visual_frames"
  DIR_AUDIO_RAW_WAV: "/HOME//Single-source/s4_data/audio_wav"
  DIR_MASK: "/HOME//Single-source/s4_data/gt_masks"
  DIR_AUDIO_LOG_MEL: "/HOME//Single-source/s4_data/audio_log_mel"

AVSBenchMS3:
  ANNO_CSV: "/HOME//Multi-sources/ms3_meta_data.csv"
  ANNO_TRAIN_CSV: "/HOME//Multi-sources/ms3_train_data.csv"
  DIR_IMG: "/HOME//Multi-sources/ms3_data/visual_frames"
  DIR_AUDIO_LOG_MEL: "/HOME//data/Multi-sources/ms3_data/audio_log_mel"
  DIR_AUDIO_RAW_WAV: "/HOME//Multi-sources/ms3_data/audio_wav"
  DIR_MASK: "/HOME//Multi-sources/ms3_data/gt_masks"

AVSSynthetic:
  ANNO_FILE: '/HOME/AVS_Synthetic/annotations.csv'
  IMAGE_DIR: "/HOME/AVS_Synthetic/images/"
  AUDIO_DIR: "/HOME/AVS_Synthetic/audios/"
  MASK_DIR: "/HOME/AVS_Synthetic/masks/"
  VGGSOUND_DICT_PATH: '/HOME/AVS_Synthetic/category_for_vggsound_audios.pkl'

sam_checkpoint: "assets/sam_vit_h_4b8939.pth"





train_dataset:
  wrapper:
    name: train
    args:
      inp_size: 1024
      augment: false
  batch_size: 2

val_dataset:
  wrapper:
    name: val
    args:
      inp_size: 1024
  batch_size: 2

test_dataset:
  wrapper:
    name: val
    args:
      inp_size: 1024
  batch_size: 1

eval_type: cod

data_norm:
  inp:
    sub:
    - 0.5
    div:
    - 0.5
  gt:
    sub:
    - 0.5
    div:
    - 0.5
  gt_rgb:
    sub:
    - 0.5
    div:
    - 0.5
model:
  name: sam
  args:
    inp_size: 1024
    loss: iou
    encoder_mode:
      name: sam
      img_size: 1024
      mlp_ratio: 4
      patch_size: 16
      qkv_bias: true
      use_rel_pos: true
      window_size: 14
      out_chans: 256
      scale_factor: 32
      input_type: fft
      freq_nums: 0.25
      prompt_type: highpass
      prompt_embed_dim: 256
      tuning_stage: 1234
      handcrafted_tune: true
      embedding_tune: true
      adaptor: adaptor
      embed_dim: 1280
      depth: 32
      num_heads: 16
      global_attn_indexes:
      - 7
      - 15
      - 23
      - 31
optimizer:
  name: adamw
  args:
    lr: 0.0002
lr_min: 1.0e-7
epoch_max: 80

multi_step_lr:
  milestones:
  - 1
  gamma: 0.1
epoch_val: 1
epoch_save: 1


#resume: 60
#start_epoch: 60
